# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-10-22 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='exit'),
            preserve_default=False,
        ),
    ]
