# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango_app', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pictures',
            new_name='picture',
        ),
    ]
