# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-29 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango_app', '0003_auto_20191028_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango_app.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango_app.UserProfile')),
            ],
        ),
    ]
