# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-29 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango_app', '0004_likedcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedcategories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='likedcategories',
            name='user',
        ),
        migrations.DeleteModel(
            name='LikedCategories',
        ),
    ]
